name: Build and Deploy Dashboard/API
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12'
    
    - name: Install dependencies
      run: |
        cd frontend_stuff
        npm install
    
    - name: Run lint and build
      run: |
        cd frontend_stuff
        npm run lint
        npm run build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version
        run: bash build.sh deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend_stuff/dist
